
[types]

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			fir = true
			redwood = true
			white_cherry = true
			pink_cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.ic2]
			rubber = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.aether_redux]
			blightwillow = true
			glacia = true
			purple_glacia = true
			gilded_oak = true
			blighted_skyroot = true

		[types.leaves_type.forbidden_arcanus]
			cherry = true
			aurum = true
			nuggety_aurum = true

	[types.wood_type]

		[types.wood_type.aether_redux]
			cloudcap = true
			fieldsproot = true
			blightwillow = true
			jellyshroom = true
			crystal = true
			glacia = true

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.mysticsbiomes]
			strawberry = true
			cherry = true
			peach = true
			maple = true
			sea_foam = true
			tropical = true
			jacaranda = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			cherry = true
			aurum = true
			edelwood = true

[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.mighty_mail]
			mail_box = true

